### ISSUE TITLE
Error compiling Sense360StarterSwift on Xcode 7.2

### ISSUE THREAD

**Issue by shaunaa126** [Sense360/Sense360StarterSwift#11]
When I try to compile, I receive the following error: /Sense360/Sense360StarterSwift/Sense360Starter/Sense360Starter/EnteredRestaurantDetector.swift:10:8: Module file was created by an older version of the compiler; rebuild 'SenseSdk' and try again: /Sense360/Sense360StarterSwift/Sense360Starter/SenseSdk.framework/Modules/SenseSdk.swiftmodule/arm64.swiftmodule
Any ideas on how to fix this issue?

**Comment by KamilMroczek** [comment]
Sorry this project is not maintained anymore. I will add a comment saying so.

But, I have updated the library to be built with Xcode 7.2, so it should work now.
